### /api/empresas recupera todas las empresas
GET http://localhost:3000/api/empresas

### /api/empresas/:id recupera una empresa por id
GET http://localhost:3000/api/empresas/1

### /api/empresas/ crea una nueva empresa
POST http://localhost:3000/api/empresas
Content-Type: application/json

{
    "nombre": "Constructora Nueva",
    "direccion": "Calle Falsa 123",
    "telefono": "555987654",
    "activa": true,
    "fecha_fundacion": "2015-05-10"
}

### /api/empresas/:id actualiza una empresa
PUT http://localhost:3000/api/empresas/1
Content-Type: application/json

{
    "nombre": "Constructora Andina Actualizada",
    "direccion": "Av. Siempre Viva 742",
    "telefono": "123456789",
    "activa": false,
    "fecha_fundacion": "2001-05-10"
}

### /api/empresas/:id elimina una empresa
DELETE http://localhost:3000/api/empresas/2
